# Generated by Django 5.0.1 on 2024-04-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_telegramusers_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='language',
            field=models.CharField(choices=[('ru', 'Ru'), ('uz', 'Uz')], default='uz', max_length=2),
        ),
    ]
