# Generated by Django 5.0.1 on 2024-05-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='step',
        ),
    ]
