# Generated by Django 5.0.1 on 2024-05-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_students_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='parent',
        ),
    ]
