# Generated by Django 5.0.1 on 2024-03-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_surname', models.CharField(max_length=100)),
                ('mother_surname', models.CharField(max_length=100)),
                ('father_birth_date', models.DateField()),
                ('mother_birth_date', models.DateField()),
                ('father_phone_number', models.CharField(max_length=13, unique=True)),
                ('mother_phone_number', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
            },
        ),
    ]
