# Generated by Django 5.0.1 on 2024-05-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='father_birth_date',
        ),
        migrations.RemoveField(
            model_name='parents',
            name='mother_birth_date',
        ),
    ]
