# Generated by Django 5.0.1 on 2024-05-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participatedstudents',
            name='is_do_homework',
        ),
        migrations.DeleteModel(
            name='AbsentStudents',
        ),
    ]
